### ISSUE TITLE
 CASIA-B dataset is not match the dataset.py

### ISSUE THREAD

**Issue by lovebobo** [xuehy/pytorch-GaitGAN#2]
Hi, the dataset.py is not fit the  CASIA-B dataset, how we should process the dataset and then run the train.py?

**Comment by xuehy** [comment]
No preprocess is needed. Did you use the CASIA-B dataset's silhouette data?

**Comment by lovebobo** [comment]
I should use the GEI of CASIA-B dataset. Now I have run the code successfully. THX
